---
title: "Boxplots MoA IAV"
author: "Chris Tjiam"
date: "2025-10-30"
output: html_document
---
## Load Dependencies
```{r}
sessionpackages <- (c("dplyr", "ggplot2", "MetBrewer", "RColorBrewer", "ggsci", "cowplot", "rmarkdown", "tidyr", "FactoMineR", "factoextra"))
lapply(sessionpackages, library, character.only = TRUE)
```

## Clean Data
```{r}
moa.dat <- read.csv("../../output/Proportion_CellIDPerSample.csv")
moa.dat <- moa.dat %>% dplyr::arrange(Timepoint)
moa.dat <- moa.dat %>% mutate(Cell_Freq = Proportion_idPerSample*100)
moa.dat <- moa.dat %>% filter(!Cell_ID %in% c("Drop", "Unknown Myeloid"))
moa.dat <- moa.dat %>% mutate(Annotation = case_when(Cell_ID == "B-cells" ~ "B-cells",
                                                     Cell_ID == "moDCs" ~ "Alv Mac",
                                                     Cell_ID == "CD4+ T-cells" ~ "CD4+ T",
                                                     Cell_ID == "Ly6C-CD8+ T-cells" ~ "Ly6C-CD8+ T",
                                                     Cell_ID == "Ly6C+CD8+ T-cells" ~ "Ly6C+CD8+ T",
                                                     Cell_ID == "Ly6C+ NK cells" ~ "Ly6C+NK",
                                                     Cell_ID == "Ly6C- NK cells" ~ "Ly6C-NK",
                                                     Cell_ID == "CD103+CD4+ T-cells" ~ "CD103+CD4+ T",
                                                     Cell_ID == "Ly6C(hi)CD64(hi) Monocytes" ~ "iMono",
                                                     Cell_ID == "cDC1" ~ "cDC1",
                                                     Cell_ID == "Monocytes" ~ "Mono",
                                                     Cell_ID == "Neutrophils" ~ "Neut",
                                                     Cell_ID == "CD206+ Macrophages" ~ "CD206+ Mac",
                                                     Cell_ID == "cDC2" ~ "cDC2",
                                                     Cell_ID == "pDCs" ~ "pDC",
                                                     Cell_ID == "CD64+MHCII- Macrophages" ~ "CD64+ Mac"))

moa.vaccine <- moa.dat %>% filter(Treatment == "Saline") 
moa.vaccine <- moa.vaccine %>% mutate(Mouse_ID = paste(Tissue, Sample_ID, Timepoint, "hr", sep = "_"))
moa.vaccine <- moa.vaccine[,c(12, 11, 1, 2, 10)]
moa.wide <- moa.vaccine %>% pivot_wider(names_from = Annotation, values_from = Cell_Freq)
moa.wide <- moa.wide %>% replace(is.na(.),0)
```

## Re-format data into List by Tissue & Annotation
```{r}
moa.pca <- PCA(moa.wide[,c(4:19)], scale.unit = TRUE, ncp = 5, graph = FALSE)
plot(moa.pca, choix = "ind")

moa.mat <- cbind(moa.wide, moa.pca[["ind"]][["coord"]])
```

## Create ggplot function to iterate through list
```{r}
# Create the ggplot object
  p <- ggplot(moa.mat, aes(x=Dim.1, y= Dim.2, colour = Tissue)) + 
       geom_point(size = 3) + 
       ylab("PCA Dimension-2 (22.2%)") + 
       xlab("PCA Dimension-1 (56.2%)") + 
       theme_classic() + 
       scale_color_npg()

p

ggsave("Figure2C_PCA.png", plot = p, width = 5, height = 4, units = "in")

```

```{r}
moa.ave <- moa.vaccine %>% group_by(Tissue, Annotation) %>% summarise(Med_Freq=median(Cell_Freq),
                                                                      Log_Med_Freq=log10(Med_Freq))

                                                levels_ylab = {c("Alv Mac",
                                                                 "cDC1",
                                                                 "cDC2",
                                                                 "CD64+ Mac",
                                                                 "CD103+CD4+ T",
                                                                 "Ly6C-CD8+ T",
                                                                 "Ly6C+CD8+ T",
                                                                 "Ly6C+NK",
                                                                 "CD4+ T",
                                                                 "CD206+ Mac",
                                                                 "pDC",
                                                                 "Ly6C-NK",
                                                                 "Mono",
                                                                 "iMono",
                                                                 "Neut",
                                                                 "B-cells"
                                                                )}

p2 <- ggplot(moa.ave, aes(x=Med_Freq, y=factor(Annotation, levels_ylab), fill = Tissue)) + 
  geom_bar(stat="identity") + 
  geom_text(aes(label = paste0(scales::number(Med_Freq, accuracy = 0.1), "%")), 
            hjust=-0.1) + 
  facet_grid(~ factor(Tissue, levels = c("Nasal Tissue", "Lung", "Spleen"))) +
  coord_cartesian(clip="off") +
  xlim(c(0,60))+
  ylab("Annotation") +
  scale_fill_npg() +
  xlab(expression("Median Frequency, %CD45"^{"+"})) +
  theme_classic() +
  theme(axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 14),
        strip.text = element_text(size = 16))
  
p2

ggsave("Figure2D_TissueFrequency.png", plot = p2, width = 10, height = 6, units = "in")
```