---
title: "2D-FD plots MoA IAV"
author: "Chris Tjiam"
date: "2025-10-30"
output: html_document
---

## Load Dependencies
```{r}
sessionpackages <- (c("dplyr", "ggplot2", "MetBrewer", "RColorBrewer", "cowplot", "rmarkdown", "ggrepel"))
lapply(sessionpackages, library, character.only = TRUE)
```


## Clean data
```{r}
moa.dat <- read.csv("../../output/Proportion_CellIDPerSample.csv")
moa.dat <- moa.dat %>% dplyr::arrange(Timepoint)
moa.dat <- moa.dat %>% mutate(Cell_Freq = Proportion_idPerSample*100)
moa.dat <- moa.dat %>% filter(!Cell_ID %in% c("Drop", "Unknown Myeloid")) #Remove unknown populations
moa.dat <- moa.dat %>% mutate(Annotation = case_when(Cell_ID == "B-cells" ~ "B-cells",
                                                     Cell_ID == "moDCs" ~ "Alv Mac",
                                                     Cell_ID == "CD4+ T-cells" ~ "CD4+ T",
                                                     Cell_ID == "Ly6C-CD8+ T-cells" ~ "Ly6C-CD8+ T",
                                                     Cell_ID == "Ly6C+CD8+ T-cells" ~ "Ly6C+CD8+ T",
                                                     Cell_ID == "Ly6C+ NK cells" ~ "Ly6C+NK",
                                                     Cell_ID == "Ly6C- NK cells" ~ "Ly6C-NK",
                                                     Cell_ID == "CD103+CD4+ T-cells" ~ "CD103+CD4+ T",
                                                     Cell_ID == "Ly6C(hi)CD64(hi) Monocytes" ~ "iMono",
                                                     Cell_ID == "cDC1" ~ "cDC1",
                                                     Cell_ID == "Monocytes" ~ "Mono",
                                                     Cell_ID == "Neutrophils" ~ "Neut",
                                                     Cell_ID == "CD206+ Macrophages" ~ "CD206+ Mac",
                                                     Cell_ID == "cDC2" ~ "cDC2",
                                                     Cell_ID == "pDCs" ~ "pDC",
                                                     Cell_ID == "CD64+MHCII- Macrophages" ~ "CD64+ Mac")) #Mutate new column for latest annotation.

moa.iav <- moa.dat %>% filter(Timepoint %in% c("48", "72", "96", "144")) %>% 
                       filter(!Treatment %in% c("Pam10ug")) %>% 
                       filter(!grepl("NTHi", Treatment)) %>% 
                       filter(Treatment %in% c("Hh", "Hh+IAV", "Saline", "Saline+IAV", "Pam1ug", "Pam1ug+IAV"))
rm(moa.dat)

moa.iav <- moa.iav %>% mutate(Pre_Treatment = case_when(Treatment == "Saline" ~ "Saline",
                                                        Treatment == "Hh" ~ "Hh",
                                                        Treatment == "Pam1ug" ~ "Pam2CSK4",
                                                        Treatment == "Saline+IAV" ~ "Saline+IAV",
                                                        Treatment == "Hh+IAV" ~ "Hh+IAV",
                                                        Treatment == "Pam1ug+IAV" ~ "Pam2CSK4+IAV"))


flat.dat <- moa.iav %>% 
            group_by(Annotation) %>% 
            mutate(scaled_freq = scale(Cell_Freq),
                   raw_freq = Cell_Freq) %>% 
            group_by(Tissue, Timepoint, Pre_Treatment, Annotation) %>% 
            summarise(Med_scaled_Freq = median(scaled_freq),
                      Med_Freq = median(raw_freq)) %>%
            group_by(Tissue, Timepoint, Annotation) %>% 
            mutate(IAV_Saline_baseline = Med_scaled_Freq[Pre_Treatment == "Saline+IAV"],
                   Hh_baseline = Med_scaled_Freq[Pre_Treatment == "Hh"],
                   Pam_baseline = Med_scaled_Freq[Pre_Treatment == "Pam2CSK4"],
                   Sal_baseline = Med_scaled_Freq[Pre_Treatment == "Saline"],
                   IAV_Saline_Med_fc = Med_scaled_Freq - IAV_Saline_baseline,
                   Pre_Treatment_Med_fc = case_when(Pre_Treatment == "Hh" ~ (Med_scaled_Freq - Hh_baseline),
                                                    Pre_Treatment == "Hh+IAV" ~ (Med_scaled_Freq - Hh_baseline),
                                                    Pre_Treatment == "Pam2CSK4" ~ (Med_scaled_Freq - Pam_baseline),
                                                    Pre_Treatment == "Pam2CSK4+IAV" ~ (Med_scaled_Freq - Pam_baseline),
                                                    Pre_Treatment == "Saline" ~ (Med_scaled_Freq - Sal_baseline),
                                                    Pre_Treatment == "Saline+IAV" ~ (Med_scaled_Freq - Sal_baseline)),
                   IAV_Saline_baseline_raw = Med_Freq[Pre_Treatment == "Saline+IAV"],
                   Sal_baseline_raw = Med_Freq[Pre_Treatment == "Saline"],
                   Percent_diff = abs((Med_Freq - IAV_Saline_baseline_raw)/Sal_baseline_raw * 100)) %>%
                   filter(!Pre_Treatment %in% c("Hh", "Saline", "Pam2CSK4", "Saline+IAV")) %>% 
                   mutate(Merge_key = paste(Tissue, Annotation, Timepoint, Pre_Treatment, sep="_"))
```

```{r}
sig.dat <- read.csv("../../output/AllComparisonsIncludingSignificance.csv")

sig.dat <- sig.dat %>% filter(Treatment1 == "Hh" & Treatment2 == "Hh+IAV" |
                              Treatment1 == "Pam1ug" & Treatment2 == "Pam1ug+IAV" |
                              Treatment1 == "Hh+IAV" & Treatment2 == "Saline+IAV" |
                              Treatment1 == "Pam1ug+IAV" & Treatment2 == "Saline+IAV") %>% 
                       filter(Timepoint %in% c("48", "72", "96", "144")) %>% 
                       filter(!Cell_ID == "Unknown Myeloid") %>% 
                       mutate(Annotation = case_when(Cell_ID == "B-cells" ~ "B-cells",
                                                     Cell_ID == "moDCs" ~ "Alv Mac",
                                                     Cell_ID == "CD4+ T-cells" ~ "CD4+ T",
                                                     Cell_ID == "Ly6C-CD8+ T-cells" ~ "Ly6C-CD8+ T",
                                                     Cell_ID == "Ly6C+CD8+ T-cells" ~ "Ly6C+CD8+ T",
                                                     Cell_ID == "Ly6C+ NK cells" ~ "Ly6C+NK",
                                                     Cell_ID == "Ly6C- NK cells" ~ "Ly6C-NK",
                                                     Cell_ID == "CD103+CD4+ T-cells" ~ "CD103+CD4+ T",
                                                     Cell_ID == "Ly6C(hi)CD64(hi) Monocytes" ~ "iMono",
                                                     Cell_ID == "cDC1" ~ "cDC1",
                                                     Cell_ID == "Monocytes" ~ "Mono",
                                                     Cell_ID == "Neutrophils" ~ "Neut",
                                                     Cell_ID == "CD206+ Macrophages" ~ "CD206+ Mac",
                                                     Cell_ID == "cDC2" ~ "cDC2",
                                                     Cell_ID == "pDCs" ~ "pDC",
                                                     Cell_ID == "CD64+MHCII- Macrophages" ~ "CD64+ Mac"))

sig.dat <- sig.dat %>% mutate(Pre_Treatment = case_when(Treatment1 == "Hh+IAV" ~ "Hh+IAV",
                                                        Treatment1 == "Pam1ug+IAV" ~ "Pam2CSK4+IAV",
                                                        Treatment2 == "Hh+IAV" ~ "Hh+IAV",
                                                        Treatment2 == "Pam1ug+IAV" ~ "Pam2CSK4+IAV"))

sig.treatment <- sig.dat %>% filter(Treatment1 == "Hh+IAV" & Treatment2 == "Saline+IAV" |
                                    Treatment1 == "Pam1ug+IAV" & Treatment2 == "Saline+IAV") %>% 
                             select(Annotation, Tissue, Timepoint, Treatment1, Treatment2, Pre_Treatment, p.value, significance) %>% 
                             dplyr::arrange(Tissue, Timepoint, Treatment1) %>% 
                             mutate(Treatment_logp = -log10(p.value),
                                    Merge_key = paste(Tissue, Annotation, Timepoint, Pre_Treatment, sep="_")) %>% 
                             select(Merge_key, Treatment_logp)

sig.iav <- sig.dat %>% filter(Treatment1 == "Hh" & Treatment2 == "Hh+IAV" |
                              Treatment1 == "Pam1ug" & Treatment2 == "Pam1ug+IAV") %>% 
                             select(Annotation, Tissue, Timepoint, Treatment1, Treatment2, Pre_Treatment, p.value, significance) %>% 
                             dplyr::arrange(Tissue, Timepoint, Treatment1) %>% 
                             mutate(IAV_logp = -log10(p.value),
                                    Merge_key = paste(Tissue, Annotation, Timepoint, Pre_Treatment, sep="_")) %>% 
                             select(Merge_key, IAV_logp)

merged.dat <- merge(flat.dat, sig.treatment, by = "Merge_key")
merged.dat <- merge(merged.dat, sig.iav, by = "Merge_key")

```


```{r}
unique_combinations <- unique(moa.iav[, c("Timepoint", "Tissue")])

rad_list <- list()
for (i in 1:nrow(unique_combinations)) {
g1 <- unique_combinations[i, "Tissue"]

# Subset the data frame based on the current combination
current_subset <- merged.dat[merged.dat$Tissue == g1,] %>% 
                  mutate(Average_logp = (Treatment_logp + IAV_logp)/2,
                         gtr_label = ifelse(Treatment_logp > 1.3 & IAV_logp > 1.3,
                                            Annotation, ""))

                                        # Store the subset in the list
                                        subset_name <- paste0(g1)
                                        rad_list[[subset_name]] <- current_subset
                                        }
```


# Create List by Tissue and Calculate FD
```{r}
# unique_combinations <- unique(moa.iav[, c("Timepoint", "Tissue")])
# 
# rad_list <- list()
# for (i in 1:nrow(unique_combinations)) {
# g1 <- unique_combinations[i, "Tissue"]
# 
# # Subset the data frame based on the current combination
# current_subset <- moa.iav[moa.iav$Tissue == g1,] %>%
#                   group_by(Annotation) %>% 
#                   mutate(scaled_freq = scale(Cell_Freq),
#                          raw_freq = Cell_Freq) %>% 
#                   group_by(Timepoint, Pre_Treatment, Annotation) %>% 
#                   summarise(Med_scaled_Freq = median(scaled_freq),
#                             Med_Freq = median(raw_freq)) %>%
#                   group_by(Timepoint, Annotation) %>% 
#                   mutate(IAV_Saline_baseline = Med_scaled_Freq[Pre_Treatment == "Saline+IAV"],
#                          Hh_baseline = Med_scaled_Freq[Pre_Treatment == "Hh"],
#                          Pam_baseline = Med_scaled_Freq[Pre_Treatment == "Pam2CSK4"],
#                          Sal_baseline = Med_scaled_Freq[Pre_Treatment == "Saline"],
#                          IAV_Saline_Med_fc = Med_scaled_Freq - IAV_Saline_baseline,
#                          Pre_Treatment_Med_fc = case_when(Pre_Treatment == "Hh" ~ (Med_scaled_Freq - Hh_baseline),
#                                                           Pre_Treatment == "Hh+IAV" ~ (Med_scaled_Freq - Hh_baseline),
#                                                           Pre_Treatment == "Pam2CSK4" ~ (Med_scaled_Freq - Pam_baseline),
#                                                           Pre_Treatment == "Pam2CSK4+IAV" ~ (Med_scaled_Freq - Pam_baseline),
#                                                           Pre_Treatment == "Saline" ~ (Med_scaled_Freq - Sal_baseline),
#                                                           Pre_Treatment == "Saline+IAV" ~ (Med_scaled_Freq - Sal_baseline)),
#                          IAV_Saline_baseline_raw = Med_Freq[Pre_Treatment == "Saline+IAV"],
#                          Sal_baseline_raw = Med_Freq[Pre_Treatment == "Saline"],
#                          Percent_diff = abs((Med_Freq - IAV_Saline_baseline_raw)/Sal_baseline_raw * 100),
#                          gtr_label = ifelse(Pre_Treatment_Med_fc > 0.5 & IAV_Saline_Med_fc > 0.5 | 
#                                             Pre_Treatment_Med_fc < -0.5 & IAV_Saline_Med_fc < -0.5 |
#                                             Pre_Treatment_Med_fc > 0.5 & IAV_Saline_Med_fc < -0.5 |
#                                             Pre_Treatment_Med_fc < -0.5 & IAV_Saline_Med_fc > 0.5 |
#                                             Pre_Treatment == "Saline+IAV" & Pre_Treatment_Med_fc > 0.5 |
#                                             Pre_Treatment == "Saline+IAV" & Pre_Treatment_Med_fc < -0.5,
#                                             Annotation, "")) %>%
#                          filter(!Pre_Treatment %in% c("Hh", "Saline", "Pam2CSK4", "Saline+IAV"))
# 
#                                         # Store the subset in the list
#                                         subset_name <- paste0(g1)
#                                         rad_list[[subset_name]] <- current_subset
#                                         }
```

```{r}
plot_and_save <- function(data_list_element, name) {
  # Create the ggplot object
  
  my_cols = c("Saline" = "grey",
              "Saline+IAV" = "grey",
               "Hh" = "#4FAFA7",
               "Hh+IAV" = "#4FAFA7",
               "Pam2CSK4" = "#4A4280",
               "Pam2CSK4+IAV" = "#4A4280" 
                )
  
  my_facet = c("2" = "2hrs",
               "6" = "6hrs",
               "24" = "24hrs",
               "48" = "48hrs",
               "72" = "72hrs",
               "96" = "96hrs",
               "144" = "144hrs"
               )
                
  p <- ggplot(data_list_element, 
              aes(x = IAV_Saline_Med_fc, y = Pre_Treatment_Med_fc, color = Pre_Treatment, label = gtr_label)) +
       geom_hline(yintercept = 0, color = "black", linetype = "solid", size = 0.1) +
       geom_vline(xintercept = 0, color = "black", linetype = "solid", size = 0.1) +
       geom_point(aes(size = Average_logp)) +
       scale_size_continuous(limits = c(0,6)) +
       geom_label_repel(aes(label.size = 15),
                       max.overlaps = Inf,
                       force = 10,
                       box.padding = 0.5) +
       facet_grid(~Timepoint, 
                  labeller = labeller(Timepoint = my_facet)
                  ) +
       scale_colour_manual(values = my_cols) +
    labs(title = name) +
       theme_classic() +
       theme(strip.text.x = element_text(size = 14),
             axis.text.x = element_text(size=16, angle = -90, hjust = 0, vjust = 0.5),
             axis.text.y = element_text(size=16, vjust = 0.5),
             axis.title.y = element_text(size=14),
             axis.title.x = element_text(size=14),
             plot.title = element_text(size=20, face = "bold", margin=margin(t=40,b=-45, l = 5)),
             legend.position="none") + 
             ylim(c(-3,3)) +
             xlim(c(-3,3)) +
             ylab("Z-score difference \n (Tx+IAV - Tx)") + xlab("Z-score difference (Tx+IAV - Saline+IAV)")

  # Define the filename
  filename <- paste0("Figure4_", name, ".png")
  
  # Save the plot
  ggsave(filename, plot = p, width = 14, height = 4, units = "in")
  plot_list[[name]] <- p
}

output_list <- names(rad_list)
plot_list <- NULL

lapply(output_list, function(name) {
  plot_and_save(rad_list[[name]], name)
})
```