---
title: "Roseplots - Hh"
author: "Chris Tjiam"
date: "2025-10-30"
output: html_document
---
## Load Dependencies
```{r}
sessionpackages <- (c("dplyr", "ggplot2", "MetBrewer", "RColorBrewer", "cowplot", "rmarkdown", "ggsci", "tidyr", "scales", "patchwork"))
lapply(sessionpackages, library, character.only = TRUE)
```

## Clean Data
```{r}
moa.dat <- read.csv("../../output/Proportion_CellIDPerSample.csv")
moa.dat <- as.data.frame(moa.dat)
moa.dat <- moa.dat %>% dplyr::arrange(Timepoint)
moa.dat <- moa.dat %>% mutate(Cell_Freq = Proportion_idPerSample*100,
                              across(c(Treatment), ~ stringr::str_replace_all(.x, "\\bPam1ug\\b", "Pam2CSK4")))


moa.vaccine <- moa.dat %>% filter(Treatment %in% c("Saline", "Hh", "Pam2CSK4")) %>% 
                           filter(!Cell_ID %in% c("Drop", "Unknown Myeloid"))

unique_combinations <- unique(moa.vaccine[, c("Tissue", "Cell_ID")])

```

## Re-format data into List by Tissue & Annotation

```{r pressure, echo=FALSE}
rad_list <- list()
for (i in 1:nrow(unique_combinations)) {
                                        g1 <- unique_combinations[i, "Tissue"]
                                        
                                        # Subset the data frame based on the current combination
                                        current_subset <- moa.vaccine[moa.vaccine$Tissue == g1,] %>% 
                                                                      group_by(Timepoint, Treatment, Cell_ID) %>% 
                                                                      summarise(Med_Freq = median(Cell_Freq)) %>%
                                                                      group_by(Timepoint, Cell_ID) %>% 
                                                                      mutate(baseline_value = Med_Freq[Treatment == "Saline"],
                                                                             Med_fc = Med_Freq / baseline_value,
                                                                             Log_Med_fc = log10(Med_fc)) 
  
                                        # Store the subset in the list
                                        subset_name <- paste0(g1)
                                        rad_list[[subset_name]] <- current_subset
}

lung.exp <- rad_list[[1]]
nasal.exp <- rad_list[[2]]
spleen.exp <- rad_list[[3]]

write.csv(lung.exp, file = "lung_med_FD.csv", row.names = FALSE)

write.csv(nasal.exp, file = "nasal_med_FD.csv", row.names = FALSE)

write.csv(spleen.exp, file = "spleen_med_FD.csv", row.names = FALSE)

```

# Figure 3

```{r}
plot_and_save <- function(data_list_element, name) {
                                                    my_cols = {c("Hh" = "#4FAFA7",
                                                                "Pam2CSK4" = "#4A4280")}
                                                    my_labs = {c("B-cells" = "B-cells",
                                                                "moDC" = "moDC",
                                                                "CD4+ T-cells" = "CD4+ T",
                                                                "Ly6C-CD8+ T-cells" = "Ly6C-CD8+ T",
                                                                "Ly6C+CD8+ T-cells" = "Ly6C+CD8+ T",
                                                                "Ly6C+ NK cells" = "Ly6C+NK",
                                                                "Ly6C- NK cells" = "Ly6C-NK",
                                                                "CD103+CD4+ T-cells" = "CD103+CD4+ T",
                                                                "Ly6C(hi)CD64(hi) Monocytes" = "iMono",
                                                                "cDC1" = "cDC1",
                                                                "Monocytes" = "Mono",
                                                                "Neutrophils" = "Neut",
                                                                "CD206+ Macrophages" = "CD206+ Mac",
                                                                "cDC2" = "cDC2",
                                                                "pDCs" = "pDC",
                                                                "CD64+MHCII- Macrophages" = "CD64+ Mac")}
                                                    levels_xlab = {c("B-cells",
                                                                 "Ly6C-CD8+ T-cells",
                                                                 "Ly6C+CD8+ T-cells",
                                                                 "Ly6C+ NK cells",
                                                                 "Ly6C- NK cells",
                                                                 "CD103+CD4+ T-cells",
                                                                 "CD4+ T-cells",
                                                                 "Monocytes",
                                                                 "Ly6C(hi)CD64(hi) Monocytes",
                                                                 "moDCs",
                                                                 "cDC1",
                                                                 "cDC2",
                                                                 "pDCs",
                                                                 "CD206+ Macrophages",
                                                                 "CD64+MHCII- Macrophages",
                                                                 "Neutrophils"
                                                                )}
                                                    my_facet = {c("2" = "2hrs",
                                                                 "6" = "6hrs",
                                                                 "24" = "24hrs",
                                                                 "48" = "48hrs",
                                                                 "72" = "72hrs",
                                                                 "96" = "96hrs",
                                                                 "144" = "144hrs"
                                                    )}
                                                                
                                                    # Create the ggplot object
                                                    p2 <- {ggplot(data_list_element %>% 
                                                                    filter(Timepoint %in% c(2, 6, 24, 48)) %>%
                                                                    filter(Treatment %in% c("Hh", "Pam2CSK4")),
                                                                 aes(x=factor(Cell_ID, levels_xlab), 
                                                                     y= Med_fc,
                                                                     fill = Treatment)) + 
                                                           geom_bar(position = "dodge", stat = "identity") +
                                                           scale_fill_manual(values = my_cols) +
                                                           scale_x_discrete(labels = my_labs) +
                                                           facet_grid(~Timepoint, 
                                                                      labeller = labeller(Timepoint = my_facet)) +
                                                           theme_classic() +
                                                           theme(panel.grid.major.y = element_line(color = "grey80", 
                                                                                                    linetype = "solid", 
                                                                                                    linewidth = 0.2),
                                                                  axis.text.x = element_text(size = 8),
                                                                  axis.title = element_blank(),
                                                                  axis.ticks = element_blank(),
                                                                  axis.line = element_blank(),
                                                                  panel.spacing.x = unit(1, "lines"),
                                                                  strip.text = element_text(size = 14),
                                                                  axis.text.y = element_text(size = 10,
                                                                                             margin = margin(r = 8, l = -20)),
                                                                  plot.title = element_text(size=16, face = "bold"),
                                                                 legend.position="none") +
                                                          geom_vline(xintercept = seq(0.5, (16-0.5), by = 1), 
                                                                     color = "grey80", 
                                                                     linetype = "solid", 
                                                                     size = 0.2) +
                                                          coord_polar(clip = "off") + 
                                                          scale_y_log10(limits = c(-10,90))
                                                    }
                   
                                                    # Define the filename
                                                    filename <- paste0("Figure3_", name, ".png")
  
                                                   # Save as .png
                                                   ggsave(filename, plot = p2, width = 7.2, height = 1.93, units = "in", scale = 1.4)
                                                   
                                                   plot_list[[name]] <- p2
                                                   }

tissue_type <- c("Nasal Tissue", "Lung", "Spleen") #indicate here the Tissue of interest)

plot_list <- NULL

plot_list <- lapply(tissue_type, function(name) {
  plot_and_save(rad_list[[name]], 
                name)
})

```

### Create Supplementary sig plot in A4 ratio
```{r}

adjustments_for_grid <- function(plot_list, ncol) {
    n <- length(plot_list)
    nrow <- ceiling(n / ncol)
    
    lapply(seq_along(plot_list), function(i) {
        p <- plot_list[[i]]
        
        # Keep legend for first plot only (patchwork will collect later)
        if (i != 1) {
            p <- p + theme(legend.position = "none")
        }
        
        p
    })
}

# Apply adjustments
ncol <- 1
plot_list_adjusted <- adjustments_for_grid(plot_list_full, ncol)

# Combine plots with patchwork and collect legend automatically
combined_plots <- wrap_plots(plot_list_adjusted, ncol = ncol) +
    plot_layout(guides = "collect") &
    labs(fill = "") &
    theme(
        legend.position = "bottom",
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 20, face = "italic"),
        panel.grid.major.y = element_line(linetype = "dotted", color = "grey70"),
        legend.key.size = unit(1, "cm")
    ) &
    guides(color = guide_legend(override.aes = list(size = 6)),
           shape = guide_legend(override.aes = list(size = 6)))


# Save tiff
ggsave("supp.png", combined_plots, height = 13, width = 20, units = "in", dpi = 600)
ggsave("supp.tiff", combined_plots, height = 13, width = 20, units = "in", dpi = 600)
```
